### ISSUE TITLE
Ip messanger help

### ISSUE THREAD

**Issue by ankurpithva** [FastCopyLab/ipmsg#12]
**Question**.
I am unable to see My pc name or any other connected devices at the list. I have checked many times about my connection to other network. Its connected with LAN and wireless both. The other connected pc is able show the own name at the list but not mine even if I connected to the same network. My side its not showing even my pc name I have set the name also at the ip messanger sertting.

Refreshed so many times also. Attached screen shot
![Screenshot (144)](https://user-images.githubusercontent.com/43958101/175763287-858259f2-7aca-43b9-8c45-20651e25b73c.png)

**Comment by shirouzu** [comment]
Can you show me ipconfig in cmd.exe?
