### ISSUE TITLE
How can I see lists that currently disconnected but connected in the past?

### ISSUE THREAD

**Issue by ProCoolGuy** [FastCopyLab/ipmsg#13]
Hi
I have a little problem.
Before I reinstall OS, I could see others that connected once but disconnected at that time(shown as disabled lists).
But now, I can only see connected lists.
Could you help me please?
Thanks in advance.

**Comment by shirouzu** [comment]
Please see.
![image](https://user-images.githubusercontent.com/1759911/179529060-0a29e924-ade1-4de2-806d-9580544b9302.png)

**Comment by ProCoolGuy** [comment]
I can't see that option in my setting window.
![image](https://user-images.githubusercontent.com/102739742/179559960-b180ceca-3260-4025-ac14-b49085c10463.png)

**Comment by shirouzu** [comment]
Please use latest version.

**Comment by ProCoolGuy** [comment]
It worked after installing the latest version.
Thank you very much 👍
