### ISSUE TITLE
Unicode colors

### ISSUE THREAD

**Issue by lollita** [FastCopyLab/ipmsg#16]
Unicode character display in black and white, do it is possible to have it colorful?

**Comment by shirouzu** [comment]
Confirm this settings.
![image](https://user-images.githubusercontent.com/1759911/186342589-9fab764c-5e49-476e-b7bd-9feef3b71091.png)

**Comment by lollita** [comment]
I set it but not change: Win10 x64, emoji from "WINDOWS." keystroke src.
![image](https://user-images.githubusercontent.com/720237/186394124-51a344e8-a361-449d-9b28-19aba472fcb7.png)
