### ISSUE TITLE
PC hang after tranfering data

### ISSUE THREAD

**Issue by ESDADeveloper** [FastCopyLab/ipmsg#17]
**Question**.
Describe your question.
When we transferred 200GB of data from one PC to another PC through Ipmsg after the PC started getting hanged what can we do now, how to solve this issue, we even restarted the PC

**Remarks**.
Please add any additional information or screenshots.

**Comment by shirouzu** [comment]
Since ipmsg only uses the official Win32 API, it is unlikely that this would cause a hang-up.
There must be another cause.
