### ISSUE TITLE
メンバーマスターからメッセージを送信しますとメンバーマスター自身にもメッセージが届きます

### ISSUE THREAD

**Issue by s-homes** [FastCopyLab/ipmsg#19]
**質問**
こんにちは。
先日から使用を始めました。ヘルプを拝見しましたが不明のためお尋ねします。
メンバーマスター1台とメンバーマスターを利用する1台という構成です。
2台ともWindows10 Pro 64bitです。

メンバーマスターからメッセージを送信しますとメンバーマスター自身にもメッセージが届きます。
メッセージが届かないようにすることは可能でしょうか。

基本的な話しで恐縮です。

**Comment by shirouzu** [comment]
聞いたことが無い現象ですね。
動画キャプチャ―等を見てみたいところです。

**Comment by s-homes** [comment]
早速ありがとうございます。
使用環境に誤りがありました。
メンバーマスターのPCはXP Pro 32bitです。
それが原因のように思いますがいかがでしょうか。

**Comment by shirouzu** [comment]
XPは既に動作環境としてサポートしていないのですが、ただそれが原因とは考えづらいですね。
https://ipmsg.org/help/ipmsghlp.htm#environment

**Comment by s-homes** [comment]
そうですか。
サポート外の環境ですのでこのまま使ってみます。
ありがとうございました。
