### ISSUE TITLE
通信のエラー？？

### ISSUE THREAD

**Issue by ghost** [FastCopyLab/ipmsg#20]
**エラー内容**
社内一部のPCで受信がされない。又は送信待ちになる
いずれも送受信いずれの問題かは不明
しかし、受信されないユーザーは送信待ちになるユーザーの画面一覧ではグレーアウトされて不在のようになっている。
受信側は更新や再起動すると受信が可能
添付ファイルも添付されず削除されているなどあるが、こちらは詳しく状況把握ができていない

**再現方法**
不明

**バージョン・環境**
 - IPMsg ver (principle, latest ver) :　5.5.1(x64)送受信いずれのPCも最新
 - OS ver:　下記の情報であってますでしょうか。
エディション	Windows 10 Pro
バージョン	21H2
インストール日	‎2020/‎06/‎05
OS ビルド	19044.2130
エクスペリエンス	Windows Feature Experience Pack 120.2212.4180.0

**スクリーンショット**
もしあれば、問題発生時のスクリーンショット
![image](https://user-images.githubusercontent.com/116548994/197480987-1a40ba5a-2a20-443a-8f79-683effee6d5d.png)

**Comment by shirouzu** [comment]
受信側PCのFirewall問題ですね。
Windows Firewall（もしくはアンチウイルス系のFirewall）で 2425/UDP&TCP がブロックされているとその現象が起きます。
Windows Firewall であれば「Windows Firewall 例外設定」などで検索、アンチウイルス系のFirewall の場合はそのマニュアルなどを参照すると良いかと思います。

**Comment by ghost** [comment]
早速ありがとうございます。
先程までグレーアウトされていたPCが何もせずに正常に表示され、
リアルタイムで送受信できました。

このような場合も同様の対応で問題なさそうでしょうか。

**Comment by ghost** [comment]
重ねて失礼致します。
ネットワークが社内でのみの使用ですが、『パブリック』のPCが複数あります。
これを『プライベート』に変更することも有効かと思いましたが、試してみても解消はされませんでした。
ファイアウォールの設定と合わせてこの設定も関係してきますでしょうか。

恐れ入りますが、ご確認の程宜しくお願い致します。

**Comment by shirouzu** [comment]
パブリックかプライベートかというモード選択より、現在モードにおいて、IP Messenger or 2425/UDP&TCP が許可設定になっているかが全てです。

なお Firewall とはいっても、起動や更新ボタンを押してから（＝UDPパケット送信）、1分間程度はUDP受信を許可することが多いです。（その間に送信すれば受信できる）

**Comment by ghost** [comment]
下記のようになっていましたが、エラーの発生しているPCでいずれもネットワーク設定を設定『プライベート』に変更し、アンチウイルスソフトの設定を下記のように『プライベート』のみに変更して解消されました。
![image](https://user-images.githubusercontent.com/116548994/197488448-4fde28a2-cb8f-4e0c-bc05-f608e87a81ed.png)

**Comment by ghost** [comment]
ありがとうございました。

社内で再設定の上、もし解消されなければ再度ご相談させてください。
