### ISSUE TITLE
20年ぶりに投稿させていただきます

### ISSUE THREAD

**Issue by hosokawa21** [FastCopyLab/ipmsg#21]
岡山県の細川です。
大変、ご無沙汰しております。
１つ質問させてもらってもいいですか？
○exchangeサーバの継続利用により、代理ブロードキャストへの
　影響が考えられるか？
愚問かもしれませんが、ネット管理者がexchangeサーバの停止に
躊躇しているので、ご意見が聞ければと思っています。

※バージョン２で長年放置していて、今回、庁舎リフォームに伴い
　サブネットマスクの変更等もあり、IP-messengerが大混乱中です。

**Comment by shirouzu** [comment]
最新版では ipmsg exchange server は使えません。
ルータ越えはIP Messenger のメンバマスター機能をお使いください。
https://ipmsg.org/help/ipmsghlp.htm#master
（なお最新版以外はサポートしておりません）

**Comment by hosokawa21** [comment]
お忙しいところ、御回答ありがとうございます。
まだ、ユーザーが２千人はいるようですので、新バージョンへの移行、正しい設定を促していきたいと思います。
