### ISSUE TITLE
解決！ありがとうございました

### ISSUE THREAD

**Issue by hosokawa21** [FastCopyLab/ipmsg#22]
細川＠岡山県です。
先日のトラブルはエクスチェンジサーバの停止で解消いたしました。
アドバイスありがとうございました。

※現在、ユーザ数が3,204を示しています。
　全員がマスターのアドレスを記載したもマスターは落ちないでしょうか？

**Comment by shirouzu** [comment]
> 全員がマスターのアドレスを記載したもマスターは落ちないでしょうか？

おそらく大丈夫のはずです。
