### ISSUE TITLE
Old user still apearing 

### ISSUE THREAD

**Issue by MK-Associates** [FastCopyLab/ipmsg#23]
In our network place, one of the user has changed the laptop but in the IP address list the old laptop is still appearing. I have uninstaled IP msg in the old laptop but still not working.

Can you show me a way were the username of the old laptop doesnt appear in the IP address list?

**Remarks**.
Please add any additional information or screenshots.

**Comment by MK-Associates** [comment]
attached as requested.. see item in red circle.. This user's laptop is not within our network but the name still appears in faded..
![Screenshot (7)](https://user-images.githubusercontent.com/122089090/210997674-6f6f94eb-88f7-4322-8bce-ec7ae83ce16f.png)

**Comment by shirouzu** [comment]
The user will be hidden after three weeks.

However, the user can be hidden immediately by following the steps below.
1. select the user
2. right-click to display the menu
3. Select "Priority Settings" → "Move to No Display" menu item.

**Comment by MK-Associates** [comment]
thanks.. this is understood and very helpful. thanks

**Comment by MK-Associates** [comment]
was a great help

**Comment by plyer6969** [comment]
Thank You So much resolved.
