### ISSUE TITLE
Multiple User Showing 

### ISSUE THREAD

**Issue by plyer6969** [FastCopyLab/ipmsg#25]
**Describe the bug**
Multiple User is Showing if we uninstall IP messenger and install it again.
or if we change the system and install it with the same IP and same user name

**To Reproduce**
 uninstall IP messenger and install it again.
change the system and install it with the same IP and same user name

**Version/Environment**
 - IP Messenger version (principle, latest ver) : version 5.6.1(x64)
 - OS ver: windows 11 version 21H2(OS build 22000.795)

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/124555661/216902162-ddd6f9bc-ac4a-4ad4-9ffa-84796de32317.png)

**Comment by shirouzu** [comment]
Please see.
https://github.com/FastCopyLab/ipmsg/issues/23#issuecomment-1373491676
