### ISSUE TITLE
indows 11 installed  ipmsg

### ISSUE THREAD

**Issue by raga2023** [FastCopyLab/ipmsg#26]
**Describe the bug**

Windows 11 installed  ipmsg  users not showing in windows 10 systems sometimes shows 

**To Reproduce**

**Version/Environment**
 - IP Messenger version (principle, latest ver) : 5.6.1
 - OS ver: windows 11

**Screenshots**

now not showing  windows 11  ipmsg users  only 8 users
![image](https://user-images.githubusercontent.com/123446165/217442570-e4e31372-e77c-4f8a-9612-c33f81ae1052.png)

now its showing all users  (windows 11 users Raghavendra & Himanshu rai
![image](https://user-images.githubusercontent.com/123446165/217442713-56c906ee-1acf-4539-b071-a8e70e3b126f.png)

**Comment by shirouzu** [comment]
IPMsg requires a firewall exclusion setting.
Please confirm the Win11 machines.
