### ISSUE TITLE
Notifications no show on Windows Lock Screen

### ISSUE THREAD

**Issue by paultey** [FastCopyLab/ipmsg#28]
**Describe the bug**
Notifications no show on Windows Lock Screen

**To Reproduce**
1. set PC 1 to lock screen 
2. send msg from PC 2 to PC 1
3. check PC 1 for notifications without unlock PC

**Version/Environment**
 - IP Messenger version (principle, latest ver) : 5.6.1
 - OS ver: Windows 11 Pro 64 bit

**Screenshots**

**Comment by shirouzu** [comment]
I think it depends on windows11 settings.
settings -> system -> notifications -> notifications
