### ISSUE TITLE
Restriction for Domain 

### ISSUE THREAD

**Issue by padghanakshay** [FastCopyLab/ipmsg#29]
Hi,
We are working on three different machines domain. Mainly we can use one domain at a time. Like you have three vpn for connection.
So can you suggest how should I restrict sending messages and files if machine domain not matching with receiver domain?

**Comment by shirouzu** [comment]
Sorry, I don't know about multiple domain / VPN.
- use refresh button in send dialog.
- disable delay send.
![image](https://user-images.githubusercontent.com/1759911/234141231-b9414ef1-f160-4f44-a89f-1827097115d9.png)

**Comment by padghanakshay** [comment]
Can this application support command line argument?

**Comment by shirouzu** [comment]
Please see.
https://ipmsg.org/help/ipmsghlp_eng.htm#cmdline
