### ISSUE TITLE
Portable-ipmsg-1.5.2.zip

### ISSUE THREAD

**Issue by blackcrack** [FastCopyLab/ipmsg#3]
**Describe the solution you'd like**
>A clear and concise description of what you want to happen.  

Yes, Sir :smiley:  , could it be possible to have a normal Zip file with the Program 
in a Folder who need only to extract to have it on a USB-Stick 
or as "simple" portable as a "Nativ in a Folder" Program (without Installer?), 
if this possible ?

**Additional context**
>Add any other context or screenshots about the feature request here.  

and the download page could be at Github (https://github.com/FastCopyLab/ipmsg), 
under "Releases" with different versions
and save you Space at your Provider..

<img src="https://user-images.githubusercontent.com/7925717/153893068-83e1bec0-8709-49a0-a877-bffe14a769a7.jpg" alt="drawing" width="200"/>

best
Blacky

```
linksave
![shootdcsdcsd2c](https://user-images.githubusercontent.com/7925717/153893068-83e1bec0-8709-49a0-a877-bffe14a769a7.jpg)
```

**Comment by FastCopyLab** [comment]
ipmsg depends on windows registry, it difficult to be portable.

**Comment by blackcrack** [comment]
Hi ,
it's there no possible to redirect into a "ini" file ?..

i have see a open source methodic anywhere to redirect and w/r into a ini.. but it's to long ago ... 
and maybe was it a linuxsource :\  Winrar use also something with Version 5.21,
https://www.win-rar.com/whatsnew.html?&L=0    => 5.20 / 3.
>3. It is possible to use WinRAR.ini file instead of Registry to store
>      WinRAR settings. You may prefer such approach if you plan to install
>      WinRAR to removable media, such as USB flash drive, and then run it
>      on different computers.
>
>      See "WinRAR.ini file" topic in "Configuration settings" chapter
>      of WinRAR help for details.  


[WinRAR.zip](https://github.com/FastCopyLab/ipmsg/files/8130571/WinRAR.zip)

but, a possible for "if exist" a .\ipmsg.ini, read the configuration from ipmsg.ini; .. and with this it should work.. imho..
is maybe a bit more code, but makes possible to have a portable and therewith it's possible for nonstationable "chatserver"
on an usb-stick, over wlan an any wlan from any City and Town ;) (if you see )

for this could it be really pretty well to have it as portable :) or startable over ssh->on a linux, with wine to have a possible for start it from a stand-alone linux anywhere in a walled-in stonewall room.. a.e. or as non-location via usb-stick to have a free opinion and so on.. for us computer friends in east for became it possible to have free words ;)  also because the actual current situation at the Ukrainians and so on.. to have different possibility's for help and cheating over different auto-relays and different servers start able if one be demolished , start the same configuration with an other ip and auto relay ip ;) ..

therefore the portable, to have a free Opinions and a free speech :) :+1: 

best

[WinRAR.zip](https://github.com/FastCopyLab/ipmsg/files/8130571/WinRAR.zip)

**Comment by blackcrack** [comment]
hmm.. pity ...
