### ISSUE TITLE
複数返信時に返信が届かない場合がある

### ISSUE THREAD

**Issue by yaji-yu** [FastCopyLab/ipmsg#30]
OS：Windows10・Windows11
IPVer：全員最新
セキュリティソフト：ウィルスバスタークラウド

同一LAN上にいる5人（仮にA・B・C・D・E）でIPを使用していたところ、
AがB・C・D・E　に同時送信。全員が無事受信。
B・C・D・Eそれぞれが同時返信。B・C・Dの同時返信は全員が受信。
しかしEの同時返信だけが、Aにのみ届き、B・C・Dに届かないという現象です。

Eのログには全員に送信したログが残っていて、
AのログにもEが全員に送信したログが残ってます。
B・C・Dのログにはそもそもログ自体はありませんでした。
それぞれが10秒以内の内に返信していました。

何か考えられることはありますでしょうか？

**Comment by shirouzu** [comment]
普通は受信側のFW設定の問題なのですが、これはちょっと違うように見えますね。
ミラーポート搭載ハブ等でネットワーク上のパケットをキャプチャして確認するしかないかもしれません。

**Comment by yaji-yu** [comment]
ミラーポート搭載ハブ、そんなものあるんですね。
すぐに用意できるかはわかりませんので、進捗があればまたご連絡させていただきます。
ご対応ありがとうございました。
