### ISSUE TITLE
NICが複数あり、メトリックを指定している場合の挙動

### ISSUE THREAD

**Issue by hiroki79** [FastCopyLab/ipmsg#31]
OS：Windows11(22H2)
IPVer：5.6.1(メンバーマスターあり)

ノートPCにてWi-Fi(メトリック2) とOnBord-LAN(メトリック1)またはドッキングステーションLAN(メトリック1)で運用した場合、
下記の様な周期で送信画面のIPアドレスが切り替わります。

Wi-Fi  約1分50秒
OnBord-LAN 約1分10秒

２台にて実験をバラバラにスタートしても、IPアドレスが同種類のアダプタに切り替え上記の周期で表示されます。

Wi-Fi表示の状態になっている時の相手に送信すると「送信できませんでした」エラーが表示されます。
しかし、メッセージは届いております。

メトリック値を色々と調整してみても、変化はありませんでした。

何か考えられることはありますでしょうか？

**Comment by shirouzu** [comment]
ipmsg.exe /NICオプションで使うIPアドレスを指定してみてください。
https://ipmsg.org/help/ipmsghlp.htm#cmdexe

**Comment by hiroki79** [comment]
早速のアドバイスありがとうございます。

/NICオプションで確かに固定はできるのですが、環境，利用目的の説明が不足しており、
/NICオプションでは対応ができません。アドバイスを頂いたのに、大変申し訳ありません。

Wi-Fi + 有線LANの対策としては利用が厳しい感じです。
/NICオプションを利用すると、指定したNICでのみ通信しているようすで、
有線LANを外してWi-Fiで利用しようとした場合、IPメッセンジャーのユーザーリストが更新されませんでした。

デスクトップＰＣで、２つのネットワークで利用している環境もあり、そちらでは/NICを問題なく利用させて頂いております。

**Comment by shirouzu** [comment]
複数のNICを同時に使うとなると、どちらのIPアドレスが使われてもやむを得ないですね。
ただその場合に、Wifi経由の場合に送信できない、という事象がよくわからないです。
Wifi側のIPアドレス経由では、宛先PCにパケットが届かない設定になっていたりしませんか？

**Comment by hiroki79** [comment]
--------------------------------------------------
宛先名
に送信できませんでした。再試行しますか？
--------------------------------------------------
こちらのエラーメッセージが表示されますが、
宛先には届いていますし、開封通知も表示されます。
また、ログを見ても、開封済みとなっております。

有線LANを抜いて、Wi-Fiのみにすれば、問題なく動作します。
有線LANを挿して、Wi-Fiオフにしても、問題なく動作します。

有線LAN を挿して、Wi-Fiオンの状態のみで、同現象が発生します。

有線LAN+Wi-Fiの時に、NICの優先順位が変動しているのかと思い、
アクティブなIPアドレスを取得するプログラムを組んで確認すると、
ずっと有線LANのIPアドレスが戻ってきます。
試しに、有線LANを抜けば、その瞬間からWi-FiのIPアドレスが戻ってきました。

**Comment by shirouzu** [comment]
なるほど。
開封通知パケットが届くのに、受信確認パケットが届かない、というのがどうにも解せないですね。
WireSharkなどでパケットを解析しないとダメかもしれません。

**Comment by hiroki79** [comment]
2425/UDPポートに対して、パケット解析をしてみれば良いですか？
とはいえ、何を注視すれば良いのかわからないので、難しいですよね。

ちなみに、下記のパターンを実験してみました。

× DELL社製 Latitude3520(Wi-Fi) + DELL社製 WD19S(有線LAN)
× DELL社製 Latitude3520(Wi-Fi) + 内蔵NIC(有線LAN)
× Panasonic社製 CF-SV2(Wi-Fi) + DELL社製 WD19S(有線LAN)
× Panasonic社製 CF-SV2(Wi-Fi) + サンワサプライ社製 USB-CVDK9(有線LAN)
〇 Panasonic社製 CF-SV2(Wi-Fi) + 内蔵NIC(有線LAN)

最後の組み合わせだけ、メトリックが考慮され、
有線LAN固定でリストに表示されました。

**Comment by shirouzu** [comment]
設定 → 設定保存/その他 → 「Console」ボタンでパケットを表示すると、送信直後の受信確認パケット(RECVMSG)はこんなログで出てきますので、それを手掛かりに出来るかどうか…？
200530.07: [568c]: ResolveMsg(2): cmd=RECVMSG (21) flags=0 from 192.168.0.7

**Comment by hiroki79** [comment]
即レスポンスを頂いている中、大変恐縮ではございますが、
調査結果は明日またはＧＷ明けにご連絡させていただきます。

**Comment by hiroki79** [comment]
WireSharkで確認した結果
問題解決になるのか、わかりませんが・・・
-----------------
起動直後の動き
-----------------
Wi-FiのIPアドレスでブロードキャストして1:を送信
有線LANのIPアドレスでメンバマスターに対して1:を送信
有線LANのIPアドレスでメンバマスターに対してIP2:を送信
有線LANのIPアドレスでメンバマスターよりIP2:をブロードキャストにて受信
有線LANのIPアドレスでメンバマスターよりIP2:を受信

-----------------
アイドル状態での動き(簡略)
-----------------
Wi-FiのIPアドレスでWi-Fiの別ＰＣよりIP2:をブロードキャストにて受信
Wi-FiのIPアドレスでWi-Fiの別ＰＣより1:をブロードキャストにて受信
Wi-FiのIPアドレスでWi-Fiの別ＰＣへ1:を送信
有線LANのIPアドレスでメンバマスターよりIP2:をブロードキャストにて受信

-----------------
メッセージを送信した動き(Wi-Fi表示されている時)
-----------------
Wi-FiへIP2:を送信
有線LANより1:を受信
Wi-FiへIP2:を送信
有線LANより1:を受信
Wi-FiへIP2:を送信
有線LANより1:を受信

-----------------
メッセージを送信した動き(有線LAN表示されている時)
-----------------
有線LANへIP2:を送信
有線LANより1:を受信

-----------------
IPメッセンジャーのConsoleで確認した
メッセージを送信した動き(Wi-Fi表示されている時)
-----------------
12929.07: [81c4]: sendto: addr=192.168.120.60 size=1101
12929.10: [81c4]: recvfrom: addr=192.168.20.106 size=62
12929.10: [81c4]: ResolveMsg(2): cmd=RECVMSG (21) flags=0 from 192.168.20.106
12929.70: [81c4]: sendto: addr=192.168.120.60 size=1101
12929.70: [81c4]: recvfrom: addr=192.168.20.106 size=62
12929.70: [81c4]: ResolveMsg(2): cmd=RECVMSG (21) flags=0 from 192.168.20.106
12930.70: [81c4]: sendto: addr=192.168.120.60 size=1101
12930.70: [81c4]: recvfrom: addr=192.168.20.106 size=62
12930.70: [81c4]: ResolveMsg(2): cmd=RECVMSG (21) flags=0 from 192.168.20.106
12931.70: [81c4]: sendto: addr=192.168.120.60 size=1165
12931.70: [81c4]: recvfrom: addr=192.168.20.106 size=62
12931.70: [81c4]: ResolveMsg(2): cmd=RECVMSG (21) flags=0 from 192.168.20.106
12932.70: [81c4]: sendto: addr=192.168.120.60 size=1165
12932.70: [81c4]: recvfrom: addr=192.168.20.106 size=62
12932.70: [81c4]: ResolveMsg(2): cmd=RECVMSG (21) flags=0 from 192.168.20.106
12938.23: [81c4]: timer done

**Comment by shirouzu** [comment]
コンソールログを見ると、送信先IPアドレスでないIPアドレスから、受信確認が届いているように見えますね。

**Comment by hiroki79** [comment]
192.168.120.60　Wi-FiのIPアドレス
192.168.20.106　有線LANのIPアドレス

メトリックを固定で設定しているので、こうなっているのかもしれませんが、
メトリックが自動でも同様の現象が発生しております。

送信先リストのIPアドレスが周期的にWi-Fiと有線LANの入れ替わりをしていますが、
これは仕様でしょうか？
メトリックの優先順位が一番高いIPアドレスを固定にする事はできませんか？

**Comment by shirouzu** [comment]
仕様ではないのですが、複数のIPアドレスを持つ端末の場合、ありうる挙動ですね。
ただ受信確認パケットのIPアドレスが（送信時から）変化することはありうる話なので、ちょっと対応を検討しておきます。

**Comment by hiroki79** [comment]
手前にて、IPアドレスを取得する簡易的なプログラムをDelphi(マニアックですみません)で検証した所、
メトリックを考慮した第一候補のみがずっと取得できていました。(10秒タイマーで取得し続ける)
（有線LANを抜いた瞬間に、Wi-FiのIPアドレスに切り替わりました）

IPメッセンジャーの送信画面でWi-FiのIPアドレスが表示されている間も、
手前製ＰＧでは有線LANのIPアドレスが取得できていました。（Wi-Fi + 有線LAN状態）
なので、何か仕様なのかな？と思っていました。

また、Wi-Fi + ドッキングステーションLAN + 内蔵LANの３つにした場合は、
IPメッセンジャーの送信画面では・・・
　Wi-Fi　約1分50秒
　ドッキングステーションLAN　約1分10秒
という状況でした。
内蔵LANよりもドッキングステーションLANの方がIPアドレスが若いから？
Wi-Fiが120セグメントで、ドッキングステーションと内蔵は20セグメントです。


ご検討、お手数おかけします。
検証など必要なことがありましたら、申し付け下さい。

**Comment by shirouzu** [comment]
ちょっとトリッキーですが、「メンバマスター利用しない」にすると交互に代わる現象は無くなるかもしれません。
（所属セグメントに１台以上、メンバマスターを利用するPCが存在すればそれでも問題なく動作すると思います）
https://ipmsg.org/help/ipmsghlp.htm#master

**Comment by hiroki79** [comment]
即レスポンス、ありがとうございます。

GW明けに検証いたします。

でも。各セグメントに１台必ず起動している必要があるのは避けたいです。

**Comment by shirouzu** [comment]
よく考えると、これは仕様通りの挙動ですね。

メンバマスターは、各セグメントについて3分に一度、定期的に所属メンバを調べ直します。
定期的に、
・セグメントAで所属メンバ一覧を調べ直す（所属PC群は、セグメントAのアドレスを返す）
・セグメントBで所属メンバ一覧を調べ直す（所属PC群は、セグメントBのアドレスを返す）
という動作が起きます。
（すると複数所属しているPCは定期的に、IPアドレスがAになったりBになったりするわけです）

そういったIPアドレスの変化を避けるには、同時の複数セグメント所属をやめるしかないですね。
（それは別の話として、IPアドレスが変化しても受信確認が届く改変は入れておきます）

**Comment by hiroki79** [comment]
> それは別の話として、IPアドレスが変化しても受信確認が届く改変は入れておきます

この対応をして頂ける事で、当初の課題は改善されます。
ありがとうございます。

「３分でリフレッシュ」これが原因なのかな？とも思っていたのですが、
表示切替の周期が約1分10秒と約1分50秒なので違うのかな？とも思ってました。
今思うと、足すと3分なので関係があったんですかね

**Comment by hiroki79** [comment]
> 「メンバマスター利用しない」にすると交互に代わる現象は無くなるかもしれません。

こちらの検証を行った所、改善されませんでした。
IPアドレスも変わるし、「送信できませんでした」エラーも表示されました。

また、IPメッセンジャーの設定画面でIPアドレスを確認すると、
交互に切り替わっている時でも、有線LANのアドレスが表示されていました。
（その都度、設定画面を表示しました）

現状ですと、Wi-Fiをオフにするしか対処方法が無い様な雰囲気です。

**Comment by shirouzu** [comment]
次期リリースまでお待ちください。
