### ISSUE TITLE
OSが日本語以外の場合の日本語UI表示

### ISSUE THREAD

**Issue by mifuki** [FastCopyLab/ipmsg#32]
**質問**
日本語以外のwindowsを使う場合は、IPMSGを日本語UIに設定できますでしょうか。

Windows11（22H2 22621.1928）を使用し、
OSの第一言語を「中国語簡体字」に設定しております。
この場合は、IPMSGの表示言語が英語になります。
UIの設定の所の「English UI」の前のチェックを入れて再起動してみて、
外して→再起動してみても、英語のままになっております。

もし日本語に戻せる方法がありましたら、
教えていただけましたら大変助かります。

**備考**
IPMSGの設定画面のキャプチャーを添付させていただきます。
![IPMsg_nc4LzPZDgZ](https://github.com/FastCopyLab/ipmsg/assets/138079754/ac9ede4d-2e28-4562-86f2-13df6f47a46f)

**Comment by shirouzu** [comment]
残念ながら、いまのところ対応方法はありません。将来バージョンで検討します。
