### ISSUE TITLE
メッセージウィンドウが表示されるが内容が表示されない

### ISSUE THREAD

**Issue by neldrip** [FastCopyLab/ipmsg#33]
いつも便利に使用させていただいています。
ありがとうございます。
現在起きている現象としては、メッセージが届くとウィンドウポップアップが表示されるのですが、
内容部分のみ何も表示されない現象が発生しています。
添付画像にキャプチャを載せさせていただきます。

ただしウィンドウの大きさを少し広げると内容がすべて表示されます。
こういった現象が出た場合にできることはありますでしょうか？
アプリの再インストールや、ファイヤーウォールの設定の見直しなどは行いましたが、
現象は変わりませんでした。
ご確認のほど宜しくお願い致します。
![ウィンドウが空](https://github.com/FastCopyLab/ipmsg/assets/19402202/bd0c937f-fcca-4f3e-8e15-3c9ffede537c)

**Comment by shirouzu** [comment]
報告されたことはないですね。
（送受信の問題ではなく、RichEditコントロールの描画上の問題っぽいですが）

対策としては、ログビューアで受信メッセージを読むとかでしょうか。（開封も可能です）
それから受信画面を大きくした状態で、受信画面の左上にあるipmsgアイコンを押して、一番下の「サイズ/フォント/位置設定」→「サイズ保存」でサイズ保存した場合に、次から受信した場合に表示内容が変化するかどうかですね。

**Comment by neldrip** [comment]
迅速なご回答ありがとうございます！早速ご指摘いただいた対応を行ってみました。
ここの設定を色々変更してうまくいかない場合は、該当不具合が起きた場合はウィンドウを少し拡大する操作を行うかログビューアから見るようにします。
ありがとうございました。

**Comment by neldrip** [comment]
教えていただいた方法を試してみましたが、やはり通知がきても内容が表示されませんでした。
ウィンドウを少し拡大する操作を行うかログビューアから見るようにします。
ありがとうございました。
