### ISSUE TITLE
Strange Message from unknown IP

### ISSUE THREAD

**Issue by Marvin0401** [FastCopyLab/ipmsg#36]
**Question**.
Hi, I got strange message from unknow IP. Please take a look at the screenshot I attached, I just want to make sure if there is no security issue. I am ok if it is sent by your sever, but it will be big issue if it is not. Thanks in advance

**Remarks**.
<img width="639" alt="image" src="https://github.com/FastCopyLab/ipmsg/assets/68524340/d6cfb4d5-66f9-45bd-99a3-27fbe259ba8d">

**Comment by shirouzu** [comment]
IP Messenger is designed for LAN.
Therefore, it does not have the ability to receive packets from outside the LAN.
You may want to check the IP address of the message to make sure it is secure.
