### ISSUE TITLE
unable to download file 

### ISSUE THREAD

**Issue by chaubeyabhi** [FastCopyLab/ipmsg#37]
**file not downloading**.
Describe your question.
(when i'm downloading file error massage is showing retry . what should i do).

**Remarks**.
Please add any additional information or screenshots.

**Comment by shirouzu** [comment]
In order to investigate, we need detailed information, please fill in the following.

**To Reproduce**
Steps to reproduce the behavior:

**Version/Environment**
 - IP Messenger version (principle, latest ver) :
 - OS ver:

**Screenshots**
If applicable, add screenshots to help explain your problem.
