### ISSUE TITLE
IPMsg.exeの戻り値について

### ISSUE THREAD

**Issue by Tetsuo-Morita** [FastCopyLab/ipmsg#38]
**質問**
2点質問させてください。
・以下のコマンド実行後、正常終了しますが、この戻り値は何を返しておりますか？(正常終了でも0以外が返りますか？)
この戻り値が定義されているならハンドリングしたいと考えております。
IPMsg.exe /MSG localhost test

・v4.5以降、ipcmdが追加されたようですので、以下でこちらのコマンドも試しましたが、user not foundになりました。
ipcmd.exe send "localhost" test
やりたいこととして、自ホストに対して、メッセージを送って、受信を確認したいです。
確かにユーザ数が0なので、自ホストを認識しないのかもしれませんが、対応策があればご教授ください。

**Comment by shirouzu** [comment]
IPMsg.exe /MSG は常に -1 が返ります。
ipcmd.exe は成功1、失敗-1になります。
（なお ipcmd では、宛先指定は UID（ログオン名-<xxxx> の形をしたもの）か ホスト名（ユーザリストに表示されているホスト名）か、IPアドレスかを指定する必要があり、localhost では届きません）

**Comment by Tetsuo-Morita** [comment]
ありがとうございます、理解できました。
ipcmd.exeも出来ました。
