### ISSUE TITLE
ログ参照をクリックしても、ログが開かない

### ISSUE THREAD

**Issue by S-Tanabe-Zeal** [FastCopyLab/ipmsg#39]
**エラー内容**
ログ参照をクリックしても、ログが開かない

**再現方法**
これまでにも数度あり、その際は再起動などで治りましたが、一切開かなくなりました。
ログを取り出せないので、再インストールも出来ずにいます。

**バージョン・環境**
 - IPMsg ver (principle, latest ver) :5.6.2
 - OS ver:win11

**スクリーンショット**

![無題](https://github.com/FastCopyLab/ipmsg/assets/146186187/e67ee238-d059-415f-905a-b5c3e7c19798)

**Comment by FastCopyLab** [comment]
聞いたことが無い現象ですね…
タスクトレイのIPMsgアイコン右クリックしてメニューを出して、最新版＆ヘルプ等 → ログ＆画像用フォルダ、を選ぶとログ関連が入ったフォルダが開きます。
そこにある、ipmsg.db というファイルが、LogViewerが使うログ用DBファイルです。
（ipmsg.log というファイルはメッセージをテキスト形式で記録したファイルになります）

たとえば、OneDrive やアンチウイルスソフトが何らかの悪さをして、ipmsg.db が正しく読めない、などの可能性があるかもしれません。

**Comment by shirouzu** [comment]
下記の手順で修復は一応可能のはずです。
（ただ再発しないよう、OneDriveから除外しておくと良いかもしれません）

1. ipmsgを終了する。
2. ipmsg.db を ipmsg.db.bak にリネーム。
3. ipmsg を起動する。
4. ログビューアを開き、メニューの「ファイル(F)」→「過去ログ取込＆削除…」を選択する。
5. 開いたダイアログから、左下の「追加」ボタンを押す。
6. ipmsg.logを選んで「開く」を押して選択。
7. 開いたファイルダイアログから、ipmsg.logを選んで「開く」を押して取り込みを実行。
