### ISSUE TITLE
Send Messageリサイズ時の挙動がおかしい

### ISSUE THREAD

**Issue by HiroyukiKobayashi-github** [FastCopyLab/ipmsg#4]
**エラー内容**
いつも便利に利用させていただいおります。
投稿方法を間違えまして、申し訳ございませんでした。再投稿させていただきます。
本日、IPMSGを5.2.0にアップデートしたところ、Send Message表示をリサイズした際の挙動がおかしくなりました。
送信ボタンの下に多めの余白が出たり、リスト内に送信ボタンがめり込んだりします。
スクリーンショットを添付します。
お忙しい中、大変恐縮ではございまずが、ご確認頂けると幸いです。

**再現方法**
Send Message画面を表示させる。
Send Messageのリストウインドウをリサイズする。（大きくしたり、小さくしたりする）

**バージョン・環境**
 - IPMsg ver (principle, latest ver) :5.2.0(x64)
 - OS ver:Windows10 Pro 21H2 64bit

**スクリーンショット**
もしあれば、問題発生時のスクリーンショット
![IPMSG](https://user-images.githubusercontent.com/101309329/157630423-7653b114-825d-42bf-a6a3-7f0fc4b611dc.jpg)
![IPMSG2](https://user-images.githubusercontent.com/101309329/157630492-cbb4e032-3a17-49f3-b43c-88cec34b0f1e.jpg)

**Comment by FastCopyLab** [comment]
ご報告ありがとうございます。
Officeのバージョンはいくつをお使いでしょうか？

とりあえず、デフォルトでは 旧バージョンと同じ挙動をするはずの v5.2.2 をリリースしましたので、動作確認してみていただけますでしょうか。
その上で、設定→詳細設定のカラー絵文字オプションを有効にした場合に、問題挙動が起きているか、もう一度確認してみて頂けますでしょうか？

**Comment by HiroyukiKobayashi-github** [comment]
早速のご対応、ありがとうございます。
インストールしているOfficeは32bit版で確認するとMicrosoft Office Apps for enterpriseとなっており、
Excelのバージョン確認すると、バージョン2108（ビルド14326.20784）で、社内で適用できる最新のビルドになっています。

IPMSGを5.2.2(x64)にバージョンアップし、ご指示の「カラー絵文字オプション」を無効にすると不具合は解消され、
有効にすると不具合が再発することを確認しました。
ご参考になれば幸いです。取り急ぎ報告致します。

**Comment by shirouzu** [comment]
動作確認ありがとうございます。
手元のOffice ver2202(14931.20120) だと問題ないので、バージョン依存問題みたいですね。

**Comment by HiroyukiKobayashi-github** [comment]
バージョン依存とのこと、了解致しました。
当面、カラー絵文字オプションは無効で利用してみます。
ご対応、ありがとうございました。
