### ISSUE TITLE
入力部分が無い送信画面について

### ISSUE THREAD

**Issue by kato-lead100** [FastCopyLab/ipmsg#40]
お世話になります。

**エラー内容**
一日の間で数回ほど入力部分が無い送信画面が起動して困っております。
返信時にも同じ画面が起動する事があります。

**再現方法**
連続でも2回程度で発生頻度もバラバラで再現性がありません。
発生後、数十分～数時間経ってから再度発生するパターンが多いです。

ディスプレイドライバの更新を行いましたが改善しませんでした。
何か対策はございますでしょうか。

**バージョン・環境**
 - IPMsg ver (最新バージョンです) :
 - Windows 10 Pro  64bit　22H2　Core i3  8GB

**スクリーンショット**
![image](https://github.com/FastCopyLab/ipmsg/assets/144968437/c22f8333-6c8e-4090-804d-659cb41120d0)

**Comment by shirouzu** [comment]
RichEditコントロールが表示されないみたいですね。
原因は不明なのですが、とりあえず下記の設定を ON or OFF にしてみて変化があるか見てみてください。
![image](https://github.com/FastCopyLab/ipmsg/assets/1759911/aea3cb07-6661-4cb5-97f7-885e297877b0)

**Comment by kato-lead100** [comment]
回答頂き有難うございます。

暫く上記を試して様子を見てみます。
