### ISSUE TITLE
ログビューワーでログが表示されない

### ISSUE THREAD

**Issue by RYOUTAUSER** [FastCopyLab/ipmsg#41]
**エラー内容**
社内で利用していますが、一部社員でログビューワーが表示されないエラーが出ております。
ログビューワーを表示すると、画面が真っ白な状態になっており、「ALL　USER」を選択してもログが表示されません。
DBを確認しましたが、どのデータベースが影響しているのか見当がつかない状況です。

**再現方法**
社用PCのキッティングを担当しており、これまでwin10 pro ４台とwin11 pro 1台の計５台作成しました。
いずれも同じ手順でインストールをし、メンバーマスターの設定をしていますが、
win10 proの２台でログビューワーが表示されない不具合が発生しております。

**バージョン・環境**
 - IPMsg ver：v5.6.3(最新バージョン)
 - OS ver:　windows10 pro 22h2 64bit

こちらの改善方法について、ご教示いただけますでしょうか。

**Comment by shirouzu** [comment]
同様の報告は長年無かったのですが、先日はじめて似た報告がありました。
 https://github.com/FastCopyLab/ipmsg/issues/39
どうも C:\users\<user>\Documentフォルダが OneDrive管理になってからトラブルが出ている印象があります。

下記の手順で修復は可能のはずです。
（ただ再発しないよう、ipmsg.logの存在するフォルダをOneDrive管理から除外したほうが良いと思います）

1. ipmsgを終了する。
2. ipmsg.db を ipmsg.db.bak にリネーム。
3. ipmsg を起動する。
4. ログビューアを開き、メニューの「ファイル(F)」→「過去ログ取込＆削除…」を選択する。
5. 開いたダイアログから、左下の「追加」ボタンを押す。
6. ipmsg.logを選んで「開く」を押して選択。
7. 開いたファイルダイアログから、ipmsg.logを選んで「開く」を押して取り込みを実行。

**Comment by kitajimajimu** [comment]
同様の症状が出たので、記載されている方法を試したのですが、エラーメッセージが出て取り込みが出来ません。データが無いというメッセージ内容でしたので、ログを確認してみると、データは確認できました。
この作業後すべてのログが消えてしまいました。どのようにすれば元にもどりますか？再インストールが必要な場合は設定を引き継ぐ方法などを教えていただけるとありがたいです。

**Comment by shirouzu** [comment]
具体的なエラーメッセージ画面のキャプチャや、ファイル一覧画面のキャプチャを貼り付けてください。

**Comment by kitajimajimu** [comment]
早々のご返信、ありがとうございます。

![image](https://github.com/user-attachments/assets/aaa2c1d1-8eb9-473e-b50f-5c58a7b60c9d)
![image](https://github.com/user-attachments/assets/ab26adce-7425-40cb-92bc-58af2da9427d)

上記のようなメッセージが出て、logテキストを選んでも読込できません。現在、メッセンジャーより送信のみ可能です。
また、DBFileはメモ帳で開くとすべてが文字化けしています。（これはそういうものなのでしょうか？）

**Comment by kitajimajimu** [comment]
すみません、1カ所訂正です。現在、メッセンジャーより送受信は行えますが、ログは一切取得できません。

**Comment by shirouzu** [comment]
DBが何らかの理由で壊れている可能性がありますねぇ…
ログビューアを開いたら、空白でしょうか？
ログビューアから、ファイル(F) → DB修復(C) を選んだ後に、ログビューアを開きなおして変化があるか見て頂けますか？

**Comment by kitajimajimu** [comment]
今朝、ログビューアーを開いたところ、ログは11/19までは表示されていました。ですが、それ以降のやり取りのログが表示されない（元の状態に戻っていた）ため、ログビューアからファイル(F) → DB修復(C) を選んだ後に、ログビューアを開きなおしましたが、変化はありませんでした。
ですが、ログインポートという画面が開き、このような表示がされ、追加を押すとファイル一覧の画面が開き、追加先を選ぶ必要があるようですが、下手に上書きしてこれ以上壊しては・・・と思い、そのままキャンセルで閉じました。

DBFileが壊れているようでしたら、DBfileのみ他のユーザーよりコピーしてファイルに上書きしてはダメでしょうか？

![image](https://github.com/user-attachments/assets/85c68f8b-cded-4573-81c6-b963aeeb866c)

**Comment by shirouzu** [comment]
インポートで壊れることは、ほぼ考えづらいですが、気になるようでしたら、インポート前に
・ipmsg を終了
・ipmsg.db をコピー/複製しておく
・ipmsg を起動
という手順で、DBファイルを保存しておくと良いと思います。

**Comment by shirouzu** [comment]
なお、ビューアでログ表示出来ている＝DBファイルは正常です。

**Comment by kitajimajimu** [comment]
インポートをしてみましたが下記のようになり、インポートできなかったです。
![image](https://github.com/user-attachments/assets/b8366277-0ca0-43e9-9acc-401b66721a4b)

**Comment by kitajimajimu** [comment]
データベースファイルも、ログも11/19から更新がされていない状況ですが、毎日メッセンジャーでやり取りはしていますので、データはあるはずなのですが・・・。

**Comment by shirouzu** [comment]
これは取り込めていないのではなく、新規データが無かった、ということっぽいですね。
（どういうわけか）ipmsgにログを書く権限が無かったか、別フォルダに書いていたか、ですね。

**Comment by kitajimajimu** [comment]
再インストールでしか解決できない感じでしょうか？
その場合、設定内容を書き出して任意の場所に保管しておいて再インストールしたIPMSGに設定を取り込めば現在の環境を復元できますでしょうか？
設定の取り込みはどちらから行えば良いですか？一応、色々確認してみたのですが、そのような項目を見つけられなかったので色々適当に触っていたので、改めて教えていただけるとありがたいです。
また、設定の取り込みをするときにレジストリの変更的なメッセージが出るのですが、それは気にせず続行して良いのでしょうか？

**Comment by shirouzu** [comment]
その前に確認ですが、ログ設定のパス名はどうなっていますか？
また現在、そのパスで示されたファイルにログは書かれていない状態でしょうか？

**Comment by kitajimajimu** [comment]
パス名は下記の通りです
Cドライブ＞ユーザーファイル＞PC名＞Documents\IPMsg\ipmsg.log
11/19以降のやり取りはログが書かれていない状態です。

**Comment by shirouzu** [comment]
なるほど。
そこがデフォルトの書き込み先なので、再インストールしても変化はなさそうですね。
そこにある ipmsg.log や ipmsg.db への書き込みをブロックしている存在がありそうです。
（書き込み権限が無いか、既に開いているプロセスが居るなど）

ファイルのプロパティ→セキュリティで権限を確認したり、sysinternalsのProcessExporelorのメニューにある、Handleから Handle or DLL substring で ipmsg.log や ipmsg.db を指定して、開いてるプロセスが無いか確認するなどでしょうか。

**Comment by kitajimajimu** [comment]
Fileのセキュリティを確認したところ読込専用に変更されていたので、チェックボックスのチェックを外すのですが、また、戻ってしまいます。

sysinternalsのProcessExporelorのメニューにある、Handleから Handle or DLL substring で ipmsg.log や ipmsg.db を指定して、開いてるプロセスが無いか確認したところ、ipmsg.logでは見つからなかったのですが、ipmsg.dbでプロセスにIPMsg.exe、PIDで14148　TypeでFile　NameでC＞ユーザー＞PC名＞ドキュメント＞IPMsg＞ipmsg.db　と表示されました。

**Comment by shirouzu** [comment]
何がそれを変えているかわかりますか？
OneDrive関連が怪しい気がしています。

**Comment by kitajimajimu** [comment]
社内PCでMicrosoft365を使用しております。OneDriveのログインで電話との紐づけを要求されますが、職場から携帯を支給されていないため、また個人の電話を紐づけることができないためこれ以上は進めません。

sysinternalsのProcessExporelorでファイルが検索されてもどうしてそれが引っかかるのかわかりません。
申し訳ありません。私の知識ではここまでが限界です。

**Comment by shirouzu** [comment]
Read only に変化させる存在が何かが判らないと、対処のしようがないですねぇ…。

やれるとしたら、OneDrive同期の影響が及ばないフォルダを作って、そこに ipmsg.log / ipmsg.db / ipmsg_img / impsg_dllinks などを移動して、ログ設定で移動先の ipmsg.log を指定した後に ipmsg 再起動、とかですかね。

**Comment by kitajimajimu** [comment]
丁寧にご対応下さり、ありがとうございます。

ドキュメント内のIPMsgフォルダを丸ごとネットワーク上の共有フォルダ（NAS)に移動して、ログ設定で移動先のipmsg.logを指定し、自分に送信、受信してみたところ、ログビューアーで表示されました。

**Comment by kitajimajimu** [comment]
他の部署からの連絡もログ表示されるようになりました。
ありがとうございました。

**Comment by shirouzu** [comment]
ご報告ありがとうございます。それはよかったです。
（IPMsg自体も、OneDrive影響のないフォルダをデフォルト利用先にしたいなぁ…良いフォルダが無いか調べてみます）
