### ISSUE TITLE
スクリーンセーバーの時の表示

### ISSUE THREAD

**Issue by loiujye** [FastCopyLab/ipmsg#42]
**質問**
送信相手のPCがスクリーンセーバーの時に表示させたい、もしくはスクリーンセーバーが解除されて通常のデスクトップ画面に戻った時に送信元からのメッセージを表示させるにはどのようにすればいいですか？

**Comment by shirouzu** [comment]
メッセージ自体を表示する方法ありませんが、着信通知に関しては、Windowsの設定 → システム → 通知とアクションで、通知設定で「ロック画面に通知を表示する」をONにすると良いかもしれません。
