### ISSUE TITLE
Need a receiving window that closes automatically

### ISSUE THREAD

**Issue by t-jay81** [FastCopyLab/ipmsg#43]
I want to use IP Messenger to call persons to come from a waiting area into my office. 
I can send a message from my iMac office pc to the Win10 presentation screen in the waiting room. I also chose a large window & font size, so everyone can read my message. But they do not have the ability to close the recv window because they haven't mouse nor keyboard.

Could you please create an Auto Close Option for the recv window that allows a self-closing after x seconds?

Thanks a lot!

**Comment by shirouzu** [comment]
It looks like a special use.
I think it would be a good idea to find or create software that closes a window with a specified title bar.
