### ISSUE TITLE
Ipmsg delayed message display 

### ISSUE THREAD

**Issue by raghav2024** [FastCopyLab/ipmsg#45]
hi we are using windows 11 os and  using ipms latest version of IPMs. When we send message to other ipmsg user messages, display late, almost one day after its  showing      

Describe your question.
(Please do not ask anything that you can figure out by experimenting at hand).

**Remarks**.
Please add any additional information or screenshots.

**Comment by shirouzu** [comment]
With that information alone, it is impossible to advise you.
