### ISSUE TITLE
IP msg delayed sending queue

### ISSUE THREAD

**Issue by prmdinesh** [FastCopyLab/ipmsg#46]
**Describe the bug**
While sending the message to other users, if it has more than 390 characters it doesn't send,  when at all sending it shows as a delayed sending queue, But that user is available.

**To Reproduce**

**Version/Environment**
 - IP Messenger version (principle, latest ver) : 5.6.16
 - OS ver:  windows 10 and windows 11

**Screenshots**

![image](https://github.com/FastCopyLab/ipmsg/assets/159764687/104dc590-b4a3-4402-8b75-d5ecca216114)

**Comment by shirouzu** [comment]
Some OS/firewalls will drop IP packets if they are fragmented.
I recommend searching with keywords such as "IP fragment packet drop policy".

**Comment by prmdinesh** [comment]
Dear shirouzu,
We checked all those cases, but still the issue persists. If I multicasting the message, it also not sending.

**Comment by shirouzu** [comment]
I think it would be a good idea to examine the packets with a LAN analyzer such as WireShark.
You will probably notice that the packet is not reaching the application layer only when the UDP packet is fragmented.
