### ISSUE TITLE
起動ができません

### ISSUE THREAD

**Issue by takeda012** [FastCopyLab/ipmsg#47]
**質問**
お世話になります。
IPメッセンジャーをインストールして、ショートカットキーはデスクトップにありますがクリックしても起動しない状況です。以前のPCにはタスクバーに表示がありましたが、そちらも無い状況です。
掲示板を確認して、ファイアウォールの許可等は試しましたが解決できません。
どのようにすれば解決できるでしょうか？ご教授いただければ幸いです。

以下↓こちらの環境です。
バージョン情報：v5.6.17
環境/OS：Windows 11 Home

**備考**
イベントビューアー　windouwsログ

![スクリーンショット (19)](https://github.com/FastCopyLab/ipmsg/assets/163392020/570a0ae8-a0eb-4722-9b54-dcddf367e94c)

**Comment by shirouzu** [comment]
起動すらしないというのは深刻ですね。
OS自体に問題が起きているように見えるのですが、イベントビューアには、他のアプリケーションのエラー記録などは出ていないでしょうか？
（いまのところ、解決策が思い浮かびません…）

**Comment by takeda012** [comment]
ご回答ありがとうございました。
今のところ他のアプリケーションのエラー記録はありません。
情報アイコンのところに、下記↓のようなログが出ていました。
（PCについては詳しくないため、全く見当違いでしたら申し訳ありません）

ログの名前:         Application
ソース:           Windows Error Reporting
日付:            2024/04/03 11:29:08
イベント ID:       1001
タスクのカテゴリ:      なし
レベル:           情報
キーワード:         
ユーザー:          SYSTEM
コンピューター:       DESKTOP-NB45AIR
説明:
障害バケット 、種類 0
イベント名: APPCRASH
応答: 使用不可
Cab ID: 0

問題の署名:
P1: IPMsg.exe
P2: 5.6.17.0
P3: 65f3cd91
P4: ntdll.dll
P5: 10.0.22621.3235
P6: a2c4352c
P7: c0000005
P8: 000000000002108d
P9: 
P10: 

添付ファイル:

これらのファイルは次の場所にある可能性があります:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_IPMsg.exe_7226f21108873788cbb0e687f568f55b75c8dd_2ccc522f_383f61dd-8505-433f-bf9c-a2c82be2551d

分析記号: 
解決策を再確認中: 0
レポート ID: e290e806-e3d3-4b2f-b4f4-65bfe74bab60
レポートの状態: 4102
ハッシュされたバケット: 
Cab GUID: 0
イベント XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-04-03T02:29:08.5059205Z" />
    <EventRecordID>11861</EventRecordID>
    <Correlation />
    <Execution ProcessID="18636" ThreadID="18076" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-NB45AIR</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="Bucket">
    </Data>
    <Data Name="BucketType">0</Data>
    <Data Name="EventName">APPCRASH</Data>
    <Data Name="Response">使用不可</Data>
    <Data Name="CabId">0</Data>
    <Data Name="P1">IPMsg.exe</Data>
    <Data Name="P2">5.6.17.0</Data>
    <Data Name="P3">65f3cd91</Data>
    <Data Name="P4">ntdll.dll</Data>
    <Data Name="P5">10.0.22621.3235</Data>
    <Data Name="P6">a2c4352c</Data>
    <Data Name="P7">c0000005</Data>
    <Data Name="P8">000000000002108d</Data>
    <Data Name="P9">
    </Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
    </Data>
    <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_IPMsg.exe_7226f21108873788cbb0e687f568f55b75c8dd_2ccc522f_383f61dd-8505-433f-bf9c-a2c82be2551d</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">e290e806-e3d3-4b2f-b4f4-65bfe74bab60</Data>
    <Data Name="ReportStatus">4102</Data>
    <Data Name="HashedBucket">
    </Data>
    <Data Name="CabGuid">0</Data>
  </EventData>
</Event>

**Comment by shirouzu** [comment]
良くわからないですね…なんだろう。
取り敢えず、再インストールしてみるとかでしょうか。

**Comment by takeda012** [comment]
ご回答ありがとうございます。

再インストールもしましたが、同じ現象でした。
とりあえずはIPメッセンジャーと互換性のあるアプリをインストールして、それで使用できているので一旦はそれを使いつつ、また再度挑戦したいと思います。
お時間をいただき、ありがとうございました。
