### ISSUE TITLE
宛先情報が含まれない

### ISSUE THREAD

**Issue by yaji-yu** [FastCopyLab/ipmsg#48]
OS：Windows10・Windows11
IPVer：5.6.17（一部旧Verのマシンもあり）

本日同一LAN上の複数人（厳密には30台近く）にIPメッセンジャーでメッセージを送信したら
宛先情報が含まれない状況が発生しました。
送信元ログにはすべての宛先が表示されていて、受信先のそれぞれのログでは、
「複数ユーザー宛」「宛先情報なし」とログビューアーでは表示されていました。

送信時に「宛先情報を含める」をOFFにもしていないですし、デフォルトはONなようです。
こういった事例はありますでしょうか？
もしくは設定のデフォルトがどこかにあったりしますでしょうか？

ちなみに複数送信したユーザーは、宛先選択時にCtrl+Aで全選択したが、
その後聞き取りの際に再現してもらおうとしたら、あれ、Ctrl+Aで選択できなくなってると言われました。
そもそもショートカットキーで宛先全選択というのも機能としてあるのでしょうか？

乱文で申し訳ありませんが、ご回答いただけますと幸いです。

**Comment by shirouzu** [comment]
仕様では31人以上で（UDPのパケットサイズ制限から）、個々のユーザ情報を入れない仕様にしています。
（30人「近く」で既に入らないというのは良く分からないですが…）

**Comment by yaji-yu** [comment]
> 仕様では31人以上で（UDPのパケットサイズ制限から）、個人のユーザ情報を入れない仕様にしています。 （30人「近く」ですでに入っていないのは良くわかりませんが…）

申し訳ありません、32人に送信してました。
また仕様を確認できておらず、申し訳ありませんでした。

Ctrl+Aで全選択というのは最初から機能してはないのでしょうか？

**Comment by shirouzu** [comment]
> Ctrl+Aで全選択というのは最初から機能してはないのでしょうか？

だと思います。
