### ISSUE TITLE
I went to refresh my ipmsg to get new msg

### ISSUE THREAD

**Issue by Nikul18** [FastCopyLab/ipmsg#49]
If some one msg me on ip then unless I refresh the ipmsg  I don't get msg and in sender's pc getmsg in qued

**Comment by shirouzu** [comment]
There is a high possibility that LAN communication is blocked by the OS/firewall, so please set IPMsg to be excluded.

**Comment by Nikul18** [comment]
How to
set IPMsg to be excluded.
________________________________

**Comment by shirouzu** [comment]
Please search "Adding Windows Firewall Exceptions" or etc.
