### ISSUE TITLE
Fails to receive Files via IP Messenger 

### ISSUE THREAD

**Issue by suraai** [FastCopyLab/ipmsg#5]
BugReport:
   Version Info (principle, latest ver) : Version v5.2.3 

   OS/Environment : Windows 10
   	
   ErrorMessage : "Connect for transfer"
   
   Error Details / Conditions :
Whenever I try to send any files, the receiver gets a message saying "Connect for transfer"
Tried to send files to different PCs, but unsuccessful.Even didnot work after reinstalling and after keeping Firewalls off.

**Comment by shirouzu** [comment]
This is due to the 2425/TCP port being blocked.
Please check if 2425/TCP is really available by using telnet command, for example.

**Comment by suraai** [comment]
Hi Shirouzu 
Can you pls let me know how to check the same, also do I need to get it unblock?

**Comment by suraai** [comment]
Thanks for your reply.

Yes 2425/TCP is available.
Also using its PIP Id I checked it is showing Disabled in UAC Virtualization.
Can you pls suggest me what shall I do ?

**Comment by shirouzu** [comment]
1. Enable telnet command in another PC.
2. Try "telnet your-pc-IPaddress 2425" in cmd.exe of another PC.

https://social.technet.microsoft.com/wiki/contents/articles/38433.windows-10-enabling-telnet-client.aspx
