### ISSUE TITLE
ipcmdでメッセージ送信時のエラー原因について

### ISSUE THREAD

**Issue by ms0460** [FastCopyLab/ipmsg#51]
**質問**
お世話になっております。

サーバー上に配置したipcmd.exeからメッセージを送信しようとしていますが、挙動が不安定になってしまいます。
具体的には、ipcmd listでユーザの一覧を取得し、一覧に存在するユーザのホスト名やIPアドレス、UIDに対してipcmd sendを実行しています。失敗したときの実行結果に「not found(...)」と表示されます。
「...」の部分は送信先が見つからなかった場合に、sendの送信先引数の値が表示されるものだと思っていますが認識あっておりますか？

「...」の部分には「P」「S」「r」「d」「6」「7」「.」など実行するたびに様々に変わります。もちろん送信先引数にはこのような文字列を設定しておらず、存在するホスト名やIPアドレス、UIDを設定しております。
送信に成功するときもあるため設定やコマンドなどは問題ないと思っています。
エラーメッセージの「...」の文字列は送信先以外に何か意味があるのでしょうか？エラーの原因を特定する上で知りたいので、教えていただける範囲であればご教示お願い致します。

**Comment by shirouzu** [comment]
> sendの送信先引数の値が表示される

そのはずですが、手元で確認したところ、確かに妙ですね。ご報告ありがとうございます。
早めに直してリリースしておきます。

**Comment by ms0460** [comment]
修正宜しくお願い致します。

体感ではありますが、同じコマンドでメッセージを送信して（手でコマンド叩いてます）、間髪入れずに送信したり間をあけて送信したりしても10回の試行に対して4回くらいはnot foundとなってしまいます。

メッセージの送信が不安定になってしまうのはこちらの環境の問題なのかとは思いますが、送れたり送れなかったりすることはよくあることなのでしょうか？

以下のコマンドを実行しています。
ipcmd /nic="<@ipAddress>" send "@userDestination" "@messageBody"
@ipAddressは送信者の固定IPアドレス、@userDestinationは送信先ユーザ（IPアドレス、ホスト名、UID）、@messageBodyはメッセージ本文の各値が入ります。
