### ISSUE TITLE
Ip messenger not working without disabling windows firewall

### ISSUE THREAD

**Issue by bolavefasfas** [FastCopyLab/ipmsg#52]
ip messenger in windows 11 does not work without disabling firewall on both deviecs. - how to fix this ?

**Comment by shirouzu** [comment]
Add settings to exclude ipmsg to Firewall.
(Or exclude TCP&UDP/2425 port)

For Windows Firewall, there should be an exclusion phase during installation (Admin privileges required)

**Comment by bolavefasfas** [comment]
> Add settings to exclude ipmsg to Firewall. (Or exclude TCP&UDP/2425 port)
> 
> For Windows Firewall, there should be an exclusion phase during installation (Admin privileges required)

For Windows Firewall, there should be an exclusion phase during installation (Admin privileges required)

this does come for some devices not for all 
If I open ports manually in windows it will work right ? any wiki on how to open ports on windows ?
Thanks

**Comment by shirouzu** [comment]
As a general rule, Firewall exclusion settings are required for all devices.
Please search on Google etc. for Windows Firewall exclusion settings.
