### ISSUE TITLE
How to use Ip messenger over 2 diffrent networks 

### ISSUE THREAD

**Issue by bolavefasfas** [FastCopyLab/ipmsg#53]
I have 2 palces to work from home and work with 3 and 2 devices 
--------------
|-Home
|-----Device1
|-----Device2
|-----Device3
|-Work
|-----Device1
|-----Device2
----------------
They are 5 kms apart 

For sending and receving files I use tailscale which lack messeging feature 

I want to connect all devices using Ip messenger to be able to messages and files 
They are all connected in 1 subnet using tailscale i am able to ping those using tailscale using direct connection 
tailscale subnet 100.64.0.0

Can we use domain or something to be able to mesage from home to work anything ?

**Comment by shirouzu** [comment]
If it's the same subnet, you should be able to use it as is.
If this is not possible, make one of the devices the member master("Become a Master"), and set the other devices to "Use/Relate to a Master"
https://ipmsg.org/help/ipmsghlp_eng.htm#master

**Comment by bolavefasfas** [comment]
> If it's the same subnet, you should be able to use it as is. If this is not possible, make one of the devices the member master("Become a Master"), and set the other devices to "Use/Relate to a Master" https://ipmsg.org/help/ipmsghlp_eng.htm#master

Work pc 1, I made it member master 

used member master ip in the tailscale ip for pc 1 from work to home deivce the device names are showing up

though files sending is qued as its not snding, its sending to the subnet ip from work 192.168.1.12 for pc 1 from work instead of using tailscale ip 

Will using domain fix this ?
I want able to find docs on how to use domain on taiscale

**Comment by bolavefasfas** [comment]
Or maybe host this in cloud https://chat-messenger.com/en/ and use it in both places

**Comment by bolavefasfas** [comment]
I want to send and recive message from home to work 
"|-Home
|-----Device1
|-----Device2
|-----Device3
|-Work
|-----Device1
|-----Device2"


both are connected via tailsale and have 2 ips 1 from router 12.168.1.xyz both both sides same subnet from router and tailscale ip 100.64.0.0 range 

Thanks 

I do have a vps where I can host any app on cloud or use tailscale 

Thanks
