### ISSUE TITLE
ログビューアの表示モニタについて

### ISSUE THREAD

**Issue by FUKUCHAN324** [FastCopyLab/ipmsg#54]
**エラー内容**
デュアルディスプレイ使用時に、ディスプレイ②でログビューアを表示した後
ディスプレイ②の電源を落とすか、Win+Pなどでシングルディスプレイに切り替えて再びログビューアを表示しようとした際
ログビューアがディスプレイ①に表示されない。(ディスプレイ②にウインドウが表示されるブラーエフェクトのようなものだけ確認できる)

**再現方法**
1.ディスプレイを2枚用意して、デュアルディスプレイの状態にする(ディスプレイ①、ディスプレイ②)
2.ディスプレイ②にログビューアを表示した後、ウインドウを閉じる
3.Win+Pでディスプレイ①のみを表示するように設定する(または、ディスプレイ②の電源を落とす)
4.再びログビューアを表示する

**バージョン・環境**
 - IPMsg ver (principle, latest ver) :v5.6.18
 - OS ver:Windows 10 Pro(22H2)

**スクリーンショット**
なし

**Comment by shirouzu** [comment]
ご報告ありがとうございます。
可能であれば次のバージョンで直しておきます。
さしあたっては、ipmsgを再起動してみてください。

**Comment by FUKUCHAN324** [comment]
ありがとうございます。
よろしくお願いします。

2024年6月17日(月) 12:00 SHIROUZU Hiroaki ***@***.***>:
