### ISSUE TITLE
メンバマスター設定 (v4.5以降）について

### ISSUE THREAD

**Issue by MameMame223** [FastCopyLab/ipmsg#55]
**質問**
お世話になっております。
VPNを使い、複数のセグメントでIPメッセンジャーを使用させていただいております。

メンバーマスターはLAN全体で1台だけ設定とありますが、
例えば、A拠点とB拠点がVPNで接続されているとすると、
マスターになるべきなのは、A拠点、B拠点合わせて1台のみ、という認識でよろしかったでしょうか。

現在、私はA拠点におり、B拠点もＰＣも見えてきているので、
メンバーマスターがどこかのPCで設定している？と思われるのですが
現在メンバーマスターを設定しているPCを特定する方法はございますでしょうか。

よろしくお願い致します。

**Comment by shirouzu** [comment]
> マスターになるべきなのは、A拠点、B拠点合わせて1台のみ、という認識でよろしかったでしょうか。

その通りです。
そしてメンバマスターが存在するセグメント以外では、1台以上の「メンバマスターを利用する」PCの参加が必要となります。

> 現在メンバーマスターを設定しているPCを特定する方法はございますでしょうか。

ちょっと判り辛いのですが、設定→その他→Consoleを開いて、送信画面で更新ボタンを押すと、
 ResolveMsgDict(2): cmd=ANSLIST_DICT (14) flags=0 from 192.168.0.2
という ANSLIST_DICT を送っている PC がいるはずなので、それがメンバマスターとなります。

**Comment by MameMame223** [comment]
ご回答ありがとうございます！
今、試しにやってみましたが、ANSLIST_DICTと書かれたものは見当たりませんでした。
メンバーマスターになっているPCがオフラインになっているためでしょうか？また明日やってみたいと思います。

ちなみに、
ResolveMsgDict(2): cmd=ANSLIST_DICT (14) flags=0 from 192.168.0.2
こちらの例ですと、192.168.0.2がメンバーマスターということになりますでしょうか？

**Comment by shirouzu** [comment]
> こちらの例ですと、192.168.0.2がメンバーマスターということになりますでしょうか？

その通りです。

**Comment by MameMame223** [comment]
ご回答ありがとうございます。メンバーマスターになっているPCが判明しました。
ただそちらのPCはDHCPで固定IPではなかったため、
固定IPの端末にメンバーマスターの機能を移したいと考えております。

その場合の手順として
①現在メンバーマスターになっているPCをメンバマスターになる→メンバーマスターを利用しないに変更する
②固定IPの端末の設定をメンバマスターになる、に変更する
③1台以上の他の端末の設定をメンバマスターを利用する、に変更し上記メンバーマスターの固定IPを設定する

という流れでよろしかったでしょうか。

**Comment by shirouzu** [comment]
だいたいその通りです。
3についての補足ですが、メンバマスターのいないLANセグメントにつき1台以上のマスタ利用PCが、「動作」している必要があります。
