### ISSUE TITLE
User Delete in IPmsg

### ISSUE THREAD

**Issue by usmanhmadse** [FastCopyLab/ipmsg#56]
**Question**.
I have a question how to delete user account that i created byself in ipmsg v.5.8.1

**Comment by shirouzu** [comment]
Please use "No Display".
(If the account is inactive for more than 6 months, it will be deleted from the user history.)

1. Select the disabled user in the Send Window.
2. Open right click menu.
3. Select "Move to No Display" menu item of "Priority Settings" of right click menu in the Send Window.

**Comment by usmanhmadse** [comment]
Thanks 😊
