### ISSUE TITLE
インターフェイス問題（メッセージ入力欄の下の部分が大きい）

### ISSUE THREAD

**Issue by mifuki** [FastCopyLab/ipmsg#58]
**質問**
いつもお世話になっております。
IP Messenger for WIN Version 5.6.19(x64) を使用しております。
インターフェイスが下図のように、メッセージ入力欄の下の部分が大きいです。
![image](https://github.com/user-attachments/assets/f87009c7-6d0a-4ceb-be14-9408aeb2defa)

例えウィンドウの一番下を、マウス左ボタンを押しながら、上にドロップするとしても、下図のように
メッセージ入力欄がなくなるまで縮みます→画面キャプチャボタン・送信ボタン・封書ボックスも上に移動して、ユーザーリストのエリアに浮いてしまいます。
![image](https://github.com/user-attachments/assets/32e6cf82-5616-4e17-b123-735e77c32f9e)

OS：Windows11 Pro 23H2（22631.4112）
設定の「アプリ」→アンインストールして、新しくインストールしてみましたが、問題は解消できませんでした。

**Comment by shirouzu** [comment]
これはウィンドウをリサイズした時の状態だと思いますが、リサイズ前は正常で、リサイズに対して、下部のボタンやエディット欄が追随しない、という挙動っぽいですね。
設定 → 詳細設定で、「送受信画面でのカラー絵文字サポート」を On/Off 逆にするとどうなるか、試してもらえますか？

**Comment by mifuki** [comment]
ご確認ご返信ありがとうございます！問題解決しました！

下記の試しをしました：
=====①====
「送受信画面でのカラー絵文字サポート」今はONの状態です。
OFFにして→適用設定して→ipMessageを開いたら問題は解決しました！
=====②====
また、「送受信画面でのカラー絵文字サポート」をONにしましたら問題が戻りました。
====以上ご報告いたします====
今のOFFの状態でしばらく使わせていただきます。

もし、原因を特定するためほかの試してほしいことがあればおしゃってください。
よろしくお願いいたします。

**Comment by shirouzu** [comment]
詳細なご確認レポートありがとうございます！
無事解決したとのことで何よりでした。
（カラー絵文字をサポートしているRichEditコントロール、ちょっと特殊なのか、環境によってリサイズが効かないっぽいのですよね…原因不明なのですが）

**Comment by mifuki** [comment]
本当の原因なのかどうかわかりませんが…
4Kディスプレイを使用しており、「拡大縮小とレイアウト」の表示サイズを200％にしています。
実験として、100％に調整して、IPMsgを再起動しましたら問題が解消しました！
200％に戻ったらまた問題が再現しましたという現象がありましたことをご報告いたします。
ご参考までに。
引き続きよろしくお願いいたします。

**Comment by shirouzu** [comment]
発現条件の特定、ありがとうございます！
（MS製RichEditコントロールの挙動の問題なので直接の修正は難しいのですが、何か回避策が取れると良いなぁ…ちょっと考えてみます）
