### ISSUE TITLE
Windows11でのIP Messengerの通知表示について

### ISSUE THREAD

**Issue by kazu731129** [FastCopyLab/ipmsg#6]
**質問**
IP Messengerはメッセージを受信するとポップアップ通知が表示されますが、
Windows11にアップデート後、そのポップアップ表示がされなくなってしまいました。
解決策などあれば、ご教授いただけると助かります。

よろしくお願いいたします。

**Comment by shirouzu** [comment]
システム設定の問題に見えますね。
IPMsgアイコン右クリック→設定→詳細設定に「トースト設定」というボタンがあり、そこから通知関連のシステム設定を開くことができます。
そこから、集中モードがONになっていないか、とか、IPMSG for Winというエントリの設定を確認してみる、とかでしょうか。

もしくは、google で「windows11 通知 表示されない」という検索をしてみると、いろいろと対処法が出てきます。

**Comment by kazu731129** [comment]
ご回答ありがとうございます。
Windows11の集中モードをオフにしたところ、従来どおりポップアップ表示されるようになりました。
ご教授、とても助かりました、ありがとうございました。
