### ISSUE TITLE
他拠点の端末　グレーアウトについて

### ISSUE THREAD

**Issue by MameMame2233** [FastCopyLab/ipmsg#60]
**質問**
A拠点とB拠点でVPNをはっており、A拠点内にあるサーバーがマスタサーバーとなっております。
A拠点とB拠点の複数クライアント端末に、メンバマスターを利用する設定でサーバーのIPアドレスを指定しております。

A拠点のクライアント端末の使用者より、B拠点の端末がすべてグレーアウトしているときがある、と連絡を受けました。
マスターとなっているサーバーは常時電源をつけ稼働させておりませんが、定期的なログインはしていません。
それが関係ありますでしょうか。

何か確認できる点などあればご教示いただけますと幸いです。
何卒よろしくお願い致します。

**Comment by shirouzu** [comment]
マスターPCでは、（ログインして）ipmsgを起動しないと、メンバマスター機能を果たせません。
