### ISSUE TITLE
Not all users are visible on IP Messenger.

### ISSUE THREAD

**Issue by girishpadia** [FastCopyLab/ipmsg#61]
**Question**.
We have started to use IP Messenger in our organization. Most of the users are using it to transfer files from one computer to another. Almost 150 users are using it. But when we see the list of users in IP Messenger screen, it shows about 40 to 50 users only. Even two nearby users sitting in same room cannot see each other. Why we are not able to see all users in IP Messenger? Please help me to understand the issue so that we can resolve it.

**Remarks**.
There are no network restrictions and no ports are blocked. All users are using Microsoft Windows 11.

**Comment by shirouzu** [comment]
It requires more information.
Is there any pattern to which users show up and which don't?
Also, how do you ensure that ports aren't blocked for all users?
