### ISSUE TITLE
URLクリックでブラウザが起動しない

### ISSUE THREAD

**Issue by neldrip** [FastCopyLab/ipmsg#63]
**エラー内容**
リンク形式になっているURLをクリックしてもブラウザが開かない現象が発生しています。
URL／Fileリンクの設定もいろいろ変更しても開けない状況です。
ログビューワーからだと普通にワンクリックで開けます。

手元に前の「ipmsg5.6.19」バージョンがあったのでインストールして試したところ、
ワンクリックで開くことができましたので最新バージョンのバグだと思われます

**再現方法**
１．最新バージョンをインストール
２．URLつきのメールを送信
３．「開封」をボタンを押して、リンク形式になっているURLをクリック
４．ブラウザが開かない

**バージョン・環境**
 - IPMsg ver (principle, latest ver) :version 5.6.19(x64)
 - OS ver:Windows 11 Pro 24H2

**Comment by shirouzu** [comment]
ご報告ありがとうございます。次のバージョンで修正しておきます。
