### ISSUE TITLE
遅延送信

### ISSUE THREAD

**Issue by tajimanoguchi** [FastCopyLab/ipmsg#64]
いつもお世話になっております。
2点ご質問があります。

1：社外の回線から社内ネットワークに接続するアプリをオンにした状態で、社内システムを利用しています。
そうするとIPMsgも社内で利用している時と同じようにリストが表示されます。
（IPMsgを起動している人、起動していない人はグレーアウトが分かる状態）
外部からIPMsgを起動している人にメッセージを送ると遅延送信キューに入ります。
この場合送り先がグレーアウトになっておらず遅延送信キューに入るのはどういった理由が考えられるでしょうか。

2：また、遅延送信キューに入った状態で受信者が更新を押してもメッセージが受信されないのどういう理由が考えられるでしょうか。

IPMsgの社内の仕様設定は、デスクトップPCとノートPCがあり、常に稼働状態のサーバーにIPMsgをインストールしてそのサーバーのＩＰをマスター。社員をメンバマスターにして使用しています。

1に関しては社内ネットワークに接続しているとはいえ外部環境からの操作になるので、ネットワークの相性的な問題で遅延送信キューに入ったりするのではないかと考えたりはしているのですが・・・
可能なら管理者様のご意見もご教授頂ければと思い質問させて頂きました。

**Comment by shirouzu** [comment]
こういう状況に見えますね。
・外部PCのIPMsgからメンバマスターPCへのUDP/2425送信はできてる＝メンバリストでは外部PCはアクティブに見える。
・送信側内部PCと外部PCが通信できていない。

外部からの接続の仕組みが、同一LANネットワークのアドレスを割り振っての接続ということであれば、外部PC側のOSファイアウォールによって、UDP/2425通信が遮断されていないか確認した方が良いかもしれません。
（なおOSファイアウォールが有効でも、自身がUDPパケットを送信して60秒間は受信可能な状態になります）

それ以外に、
・別LANネットワークのアドレス範囲にあり、内部側は適切なデフォルトゲートウェイが設定されたPCのみ通信可能
・NAPT的なアドレス変換が噛んでる
なども考えられますが、前者だと正しいデフォルトゲートウェイ設定で対処可能ですが、後者だと対応は難しいという感じでしょうか。
