### ISSUE TITLE
IPMsg window size bug

### ISSUE THREAD

**Issue by TopETH** [FastCopyLab/ipmsg#65]
**Describe the bug**
IPMsg shows only gray screen and cannot see its textbox.

**To Reproduce**
After save size/header and keep position, if I open ipmsg, it sometimes shows like the following.

**Version/Environment**
 - IP Messenger version (principle, latest ver) : 5.6.18(x64)
 - OS ver: Windows 11 Pro (23H2, 22631.2428)

**Screenshots**
![image](https://github.com/user-attachments/assets/3a8c4b2b-5534-44d5-b300-33ed7fe1b67e)

**Comment by shirouzu** [comment]
Please try turning off the Color Emoji support option.
https://github.com/FastCopyLab/ipmsg/issues/58
![image](https://github.com/user-attachments/assets/6a0b6a45-48dc-4f26-8b49-dde62a1f259e)

**Comment by TopETH** [comment]
> Please try turning off the Color Emoji support option. [#58](https://github.com/FastCopyLab/ipmsg/issues/58) ![image](https://github.com/user-attachments/assets/6a0b6a45-48dc-4f26-8b49-dde62a1f259e)

It Worked
