### ISSUE TITLE
missing some message when run with multi IPv6 for each PC

### ISSUE THREAD

**Issue by jacklondonchen** [FastCopyLab/ipmsg#9]
**Describe the bug**
missing some message when run with multi IPv6

**To Reproduce**
In China, normally we got two IPv6 address automatically, one of them is temp IPv6.  When two computer send/receive messages, some of them will be missed.
I guess that is because of two IPv6 address in each of the computers.
I write a new app named as zg-ipchat with Java, at https://www.zheguisoft.com/en-us/software_tools-zg_ipchat.htm .
it seems work well. but I am afraid will not continually update it later.
So, would you add function to support multi IPv6 for each PC?

The zg-ipchat has some different features:
a. support multi IPv4/IPv6 for one friend's PC.
b. use friend list + stranger, instead of broadcast.
c. configuration file in json, multi-language file in json.
d. code with java, swing, apache mina, eclipse. support windows, ubuntu, debian.
e. only text chat, no file transfer, no encryption by now.

**Version/Environment**
 - IP Messenger version (principle, latest ver) : 5.3.2(x64)
 - OS ver: Windows 10

**Screenshots**
无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv6 地址 . . . . . . . . . . . . : 2409:8a1e:90a2:b2c0:b82d:ece4:fbff:86b8
   临时 IPv6 地址. . . . . . . . . . : 2409:8a1e:90a2:b2c0:7c5e:abe1:812c:d0ff
   本地链接 IPv6 地址. . . . . . . . : fe80::b82d:ece4:fbff:86b8%17
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.156
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : fe80::1%17
                                       192.168.1.200

**Comment by shirouzu** [comment]
I will consider it.
